name: CI/CD for Chrona Backend

on:
  push:
    branches:
      - production  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/chrona-backend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/chrona-backend:latest

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/chrona-backend:latest
            sudo docker stop chrona-backend || true
            sudo docker rm chrona-backend || true
            sudo docker run -d -p 443:8000 --env-file /home/ec2-user/.env --name chrona-backend ${{ secrets.DOCKER_USERNAME }}/chrona-backend:latest